version: '3.8'

services:
  # Vue.js Frontend Service
  vue-frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "80:80"
    env_file:
      - .env

  # Flask Backend
  flask-backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
