version: '3.8'
services:
  # Vue.js Frontend Service
  hostspace-frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
    container_name: frontend
    env_file:
      - .env

  # Flask Backend
  hostspace-backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"
    container_name: backend
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    env_file:
      - .env
