version: '3.8'
services:
  # Vue.js Frontend Service
  vue-frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env

  # Flask Backend
  flask-backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    env_file:
      - .env
