apiVersion: v1
kind: Service
metadata:
  name: hostspace-backend
  namespace: hostspace-namespace
spec:
  selector:
    app: hostspace-backend
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  