apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostspace-frontend
  namespace: hostspace-namespace
  labels:
    app: hostspace-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostspace-frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: hostspace-frontend
        tier: frontend
    spec:
      containers:
        - name: hostspace-frontend
          image: fynewily/hostspace-challenge:frontend-v1.1
          ports:
            - containerPort: 80
          env:
          - name: VUE_APP_PROXY_URL
            valueFrom:
              configMapKeyRef:
                name: hostspace-configmap
                key: vue_app_proxy_url