name: Build and Push Docker images to Docker Hub

on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Read and increment version
        run: |
          current_version=$(cat VERSION)
          new_version=$(echo "$current_version + 0.1" | bc)
          echo $new_version > VERSION
          echo "BUILD_VERSION=$new_version" >> $GITHUB_ENV
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: fynewily/hostspace-challenge:frontend-v${{ env.BUILD_VERSION }}
          file: frontend.Dockerfile
      
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: fynewily/hostspace-challenge:backend-v${{ env.BUILD_VERSION }}
          file: backend.Dockerfile